#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100.
for((m=1;m<=100;m++))
do
	if ((m % 15 == 0))
	then
		echo "FizzBuzz"
	elif ((m % 3 == 0))
	then
		echo "Fizz"
	elif ((m % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$m"
	fi
done
