#!/usr/bin/env bash
#Bash script that displays the content of the file

IFS=:
while read -r USERNAME PASSWORD USERID GROUPID USERIDINFO HOME CMD
do
	echo "The user $USERNAME is part of the $GROUPID gang, lives in $HOME and rides $CMD. $USERID's place is protected by the passcode $PASSWORD,	more info about the user here: $USERIDINFO"
DONE < /etc/passwd
