#!/usr/bin/env bash
#Bash script that displays Best School 10 times with Hi on 9th.
num=1
while [ $num -le 10 ]
do
        echo "Best School"
	if [ $num -eq 9 ]
	then
		echo "Hi"
	fi
        ((num=num+1))
done
