#!/usr/bin/env bash
#Bash script that loops from 1 to 10.
num=1
while [ $num -le 10 ]
do
        if [ $num -eq 8 ]
		then
			echo "good luck"
	elif [ $num -eq 4 ]
	then
		echo "bad luck"
        else
                echo "Best School"
        fi
        ((num=num+1))
done
