#!/usr/bin/env bash
#Bash script that displays the clock.
timehour=0
while [ $timehour -le 12 ]
do
	echo "Hour : $timehour"
	timeminutes=1
	while [ $timeminutes -lt 60 ]
	do
		echo "$timeminutes"
		((timeminutes=timeminutes+1))
	done
	((timehour=timehour+1))
done
